use_frameworks!

platform :ios, '9.0'

target 'JIMediator_Example' do
  pod 'JIMediator', :path => '../'

  target 'JIMediator_Tests' do
    inherit! :search_paths

    pod 'URLNavigator'
    
  end
end
